### ISSUE TITLE
Support Arch Linux 🐧

### ISSUE THREAD

**Issue by jairo-ab** [zepfietje/minimal-code#1]
Could you show a step-by-step how to do the same procedure in linux? 🐧

**Comment by zepfietje** [comment]
Hey @jairo-ab, thanks for opening an issue!

I don't run Arch Linux, so won't be able to write the steps myself.
Additionally, you'll just have to install the same packages/font, which can also be done manually.

If you do know the exact CLI commands though, feel free to open a pull request.
I'll always consider merging that in!
